/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2022-03-17 18:41:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.js\" integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" integrity=\"sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />    <link rel=\"stylesheet\" href=\"join.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/join.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/join.js\"></script>\r\n");
      out.write("    <title>회원가입</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"main_box\">\r\n");
      out.write("        <h1 class=\"title\"><a href=\"\">SkyDiary</a></h1>\r\n");
      out.write("    \r\n");
      out.write("        <h1></h1>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form_box\">\r\n");
      out.write("\r\n");
      out.write("            <form id=\"join_form\" action=\"join\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("                <!-- 로그인 -->\r\n");
      out.write("                <div class=\"input_box\">\r\n");
      out.write("                    <label for=\"id\">아이디</label>\r\n");
      out.write("                    <input type=\"text\" id=\"id\" name=\"id\" placeholder=\"아이디\">\r\n");
      out.write("                    <span class=\"icon\">\r\n");
      out.write("                        <i class=\"fa-solid fa-check id_check\"></i>\r\n");
      out.write("                        <i class=\"fa-solid fa-exclamation id_false\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span id=\"id_msg\" class=\"msg\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 비밀번호 -->\r\n");
      out.write("                <div class=\"input_box\">\r\n");
      out.write("                    <label for=\"pw\">비밀번호</label>\r\n");
      out.write("                    <input type=\"password\" id=\"pw\" name=\"pw\" placeholder=\"비밀번호\">\r\n");
      out.write("                    <span class=\"icon\">\r\n");
      out.write("                        <i class=\"fa-solid fa-check pw_check\"></i>\r\n");
      out.write("                        <i class=\"fa-solid fa-exclamation pw_false\"></i>                \r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span id=\"pw_msg\" class=\"msg\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 비밀번호 확인 -->\r\n");
      out.write("                <div class=\"input_box\">\r\n");
      out.write("                    <label for=\"pw2\">비밀번호 확인</label>\r\n");
      out.write("                    <input type=\"password\" id=\"pw2\" placeholder=\"비밀번호 확인\">\r\n");
      out.write("                    <span class=\"icon\">\r\n");
      out.write("                        <i class=\"fa-solid fa-check pw2_check\"></i>\r\n");
      out.write("                        <i class=\"fa-solid fa-exclamation pw2_false\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span id=\"pw2_msg\" class=\"msg\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 이름 -->\r\n");
      out.write("                <div class=\"input_box\" >\r\n");
      out.write("                    <label for=\"name\">이름</label>\r\n");
      out.write("                    <input type=\"text\" id=\"name\" name=\"name\" placeholder=\"이름\">\r\n");
      out.write("                    <span class=\"icon\">\r\n");
      out.write("                        <i class=\"fa-solid fa-check name_check\"></i>\r\n");
      out.write("                        <i class=\"fa-solid fa-exclamation name_false\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span id=\"name_msg\" class=\"msg\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 이메일 -->\r\n");
      out.write("                <div class=\"input_box email_box\" >\r\n");
      out.write("                    <label for=\"email\">이메일 확인</label>\r\n");
      out.write("                    <input type=\"text\" id=\"email\" name=\"email\" placeholder=\"이메일\">\r\n");
      out.write("                    <span class=\"icon email_icon\">\r\n");
      out.write("                        <i class=\"fa-solid fa-check email_check\"></i>\r\n");
      out.write("                        <i class=\"fa-solid fa-exclamation email_false\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <input type=\"button\" class=\"btn\" id=\"authCodeSend_btn\" value=\"전송\">\r\n");
      out.write("                    <span id=\"email_msg\" class=\"msg\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 인정번호 확인 박스 -->\r\n");
      out.write("                <div class=\"input_box auth_box\">\r\n");
      out.write("                    <label for=\"authCode\"></label>\r\n");
      out.write("                    <input type=\"text\" id=\"authCode\" placeholder=\"인증번호\">\r\n");
      out.write("                    <span class=\"icon auth_icon\">\r\n");
      out.write("                        <i class=\"fa-solid fa-check auth_check\"></i>\r\n");
      out.write("                        <i class=\"fa-solid fa-exclamation auth_false\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <input type=\"button\" class=\"btn\" id=\"authCodeCheck_btn\" value=\"인증\">\r\n");
      out.write("                    <span id=\"auth_msg\" class=\"msg\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"submit\" class=\"btn join\" id=\"join_btn\" value=\"회원가입\">\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
